### ISSUE TITLE
statistical measure

### ISSUE THREAD

**Issue by zhengj2007** [obcs/obcs#1]
_From [zhengj2...@gmail.com](https://code.google.com/u/100840849128868144328/) on March 18, 2014 18:17:02_

http://purl.obolibrary.org/obo/OBCS_0000051 Current definition:
a measurement datum that represents a number (statistic) whose size indicates the magnitude of some quantity of interest.

It is little bit hard to understand. Do we need to improve it? 
Is it same as 'statistic'? http://en.wikipedia.org/wiki/Statistic Can we say it is the output of statistical data analysis?

_Original issue: http://code.google.com/p/obcs/issues/detail?id=1_

**Comment by yongqunh** [comment]
Yes. Its alternative term is ‘statistic’.

Oliver
