### ISSUE TITLE
random selection

### ISSUE THREAD

**Issue by zhengj2007** [obcs/obcs#3]
_From [zhengj2...@gmail.com](https://code.google.com/u/100840849128868144328/) on March 24, 2014 17:31:08_

Whether 'random selection' is a kind of 'data collection' and realizes some (concretizes some 'randomization sampling design')?

_Original issue: http://code.google.com/p/obcs/issues/detail?id=3_

**Comment by yongqunh** [comment]
Appears true:
http://www.statisticssolutions.com/difference-between-random-selection-and-random-assignment/
http://www.socialresearchmethods.net/kb/random.htm
http://psychology.about.com/od/rindex/fl/What-Is-Random-Selection.htm

Oliver
